version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app  # Mounts server code for live reload
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app  # Mounts client code for live reload
      - /app/node_modules  # Ensures node_modules is not overwritten
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables hot reloading
      - DISABLE_ESLINT_PLUGIN=true  # Disables ESLint in Create React App
    depends_on:
      - server
